apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-bronze"
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/data/lv-1
  persistentVolumeReclaimPolicy: Recycle